# Braid Mock Server Configuration
# This file contains all settings for the Braid mock server

server:
  port: 8443
  root_dir: "./mock-data"

proxy:
  url: "https://api.example.com"  # Example: "http://api.example.com"
  insecure_verify: true

tls:
  enabled: true
  cert_file: "cert/cert.pem"
  key_file: "cert/key.pem"
  generate_cert: false

cors:
  enabled: true
  allow_origins: "*"
  allow_methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
  allow_headers: "Content-Type, Authorization, Subscribe, Version, Parents, x-keep-alive, x-client-info, x-fingerprint"
  allow_credentials: false
  max_age: 86400